-- Utilora 管理端一次性脚本
-- 生产控制型折扣：由管理员在后台维护 promotions，本阶段强制 payment_required=false，不接支付。
-- 全部管理端功能改完后，由人工在生产 SQL Editor 整份执行。请勿提前执行。
-- 依赖：public.is_admin()、purchase_intents、promotions、entitlement_grants、analytics_events、admin_users
-- A-01 grant/revoke：见 migrations/202608310001_admin_grant_entitlement.sql（请一并执行）
-- A-02 风控台：见 migrations/202608310002_admin_risk_console.sql（admin_risk_console RPC）
--
-- 重要：本分支上此文件曾因 API 推送截断。完整函数体请以 main 分支
--   supabase/admin-ops.sql
-- 为准复制后执行；或从本仓库历史提交 959d4b2 同路径恢复。
-- A-02 仅新增 admin_risk_console，不替代上述完整 ops 脚本。
