-- 在 Supabase SQL Editor 中整份执行；不会删除既有统计数据
-- 升级后管理端可使用：环比、新/回访客、自定义日期、每日工具使用次数
create table if not exists public.analytics_events(
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null check(event_type in(
    'page_view','tool_use','homepage_view','free_tool_use','pro_click','demo_enter',
    'login_success','workspace_enter','bank_use','receivable_use','month_end_use',
    'pricing_view','purchase_intent'
  )),
  tool_slug text,
  path text,
  session_id text,
  referrer text,
  device text,
  browser text
);
alter table public.analytics_events drop constraint if exists analytics_events_event_type_check;
alter table public.analytics_events add constraint analytics_events_event_type_check check (event_type in (
  'page_view','tool_use','homepage_view','free_tool_use','pro_click','demo_enter',
  'login_success','workspace_enter','bank_use','receivable_use','month_end_use',
  'pricing_view','purchase_intent'
));

alter table public.analytics_events add column if not exists session_id text;
alter table public.analytics_events add column if not exists referrer text;
alter table public.analytics_events add column if not exists device text;
alter table public.analytics_events add column if not exists browser text;
create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_tool_idx on public.analytics_events(event_type, tool_slug);
create index if not exists analytics_events_type_created_idx on public.analytics_events(event_type, created_at desc);
alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from anon, authenticated;

-- 每个访客每天最多一行；使用 Asia/Shanghai 作为日期边界
create table if not exists public.analytics_daily_visitors(
  visitor_id text not null,
  visit_day date not null default ((now() at time zone 'Asia/Shanghai')::date),
  first_seen_at timestamptz not null default now(),
  path text,
  referrer text,
  device text,
  browser text,
  primary key(visitor_id, visit_day)
);
alter table public.analytics_daily_visitors enable row level security;
revoke all on public.analytics_daily_visitors from anon, authenticated;
create index if not exists analytics_daily_visitors_day_idx on public.analytics_daily_visitors(visit_day);
create index if not exists analytics_daily_visitors_visitor_idx on public.analytics_daily_visitors(visitor_id);

-- 从旧事件安全迁移：只复制去重后的记录，不删除原数据
insert into public.analytics_daily_visitors(visitor_id, visit_day, first_seen_at, path, referrer, device, browser)
select distinct on (session_id, (created_at at time zone 'Asia/Shanghai')::date)
  session_id,
  (created_at at time zone 'Asia/Shanghai')::date,
  created_at,
  path,
  referrer,
  device,
  browser
from public.analytics_events
where event_type = 'page_view' and session_id is not null
order by session_id, (created_at at time zone 'Asia/Shanghai')::date, created_at
on conflict (visitor_id, visit_day) do nothing;

drop function if exists public.track_analytics_event(text, text, text);
drop function if exists public.track_analytics_event(text, text, text, text, text, text, text);
create function public.track_analytics_event(
  p_event_type text,
  p_tool_slug text default null,
  p_path text default null,
  p_session_id text default null,
  p_referrer text default null,
  p_device text default null,
  p_browser text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_event_type not in (
    'page_view',
    'tool_use',
    'homepage_view',
    'free_tool_use',
    'pro_click',
    'demo_enter',
    'login_success',
    'workspace_enter',
    'bank_use',
    'receivable_use',
    'month_end_use',
    'pricing_view',
    'purchase_intent'
  ) then
    raise exception 'invalid event type';
  end if;
  if length(coalesce(p_tool_slug, '')) > 80
    or length(coalesce(p_path, '')) > 200
    or length(coalesce(p_session_id, '')) > 80
    or length(coalesce(p_referrer, '')) > 160 then
    raise exception 'invalid analytics payload';
  end if;
  if p_event_type = 'page_view' and nullif(p_session_id, '') is not null then
    insert into public.analytics_daily_visitors(visitor_id, path, referrer, device, browser)
    values (p_session_id, nullif(p_path, ''), nullif(p_referrer, ''), nullif(p_device, ''), nullif(p_browser, ''))
    on conflict (visitor_id, visit_day) do nothing;
  elsif p_event_type <> 'page_view' then
    insert into public.analytics_events(event_type, tool_slug, path, session_id, referrer, device, browser)
    values (
      p_event_type,
      nullif(p_tool_slug, ''),
      nullif(p_path, ''),
      nullif(p_session_id, ''),
      nullif(p_referrer, ''),
      nullif(p_device, ''),
      nullif(p_browser, '')
    );
  end if;

end
$$;
revoke all on function public.track_analytics_event(text, text, text, text, text, text, text) from public;
grant execute on function public.track_analytics_event(text, text, text, text, text, text, text) to anon, authenticated;

drop function if exists public.get_analytics_summary();
drop function if exists public.get_analytics_summary(integer);
drop function if exists public.get_analytics_summary(integer, date, date);
create function public.get_analytics_summary(
  p_days integer default 30,
  p_start date default null,
  p_end date default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
  start_day date;
  end_day date;
  prev_start date;
  prev_end date;
  start_at timestamptz;
  prev_end_at timestamptz;
  range_days integer;
  today_day date;
begin
  if not public.is_admin() then
    raise insufficient_privilege;
  end if;

  today_day := (now() at time zone 'Asia/Shanghai')::date;
  end_day := least(coalesce(p_end, today_day), today_day);
  if p_start is not null then
    start_day := p_start;
  else
    p_days := greatest(1, least(coalesce(p_days, 30), 365));
    start_day := end_day - (p_days - 1);
  end if;
  if start_day > end_day then
    raise exception 'invalid date range';
  end if;
  if end_day - start_day > 365 then
    start_day := end_day - 365;
  end if;

  range_days := (end_day - start_day) + 1;
  prev_end := start_day - 1;
  prev_start := prev_end - (range_days - 1);
  start_at := start_day::timestamp at time zone 'Asia/Shanghai';
  prev_end_at := start_day::timestamp at time zone 'Asia/Shanghai';

  select jsonb_build_object(
    'days', range_days,
    'start', to_char(start_day, 'YYYY-MM-DD'),
    'end', to_char(end_day, 'YYYY-MM-DD'),
    'total_views', (
      select count(*) from public.analytics_daily_visitors
      where visit_day between start_day and end_day
    ),
    'unique_visitors', (
      select count(distinct visitor_id) from public.analytics_daily_visitors
      where visit_day between start_day and end_day
    ),
    'today_views', (
      select count(*) from public.analytics_daily_visitors
      where visit_day = today_day
    ),
    'yesterday_views', (
      select count(*) from public.analytics_daily_visitors
      where visit_day = today_day - 1
    ),
    'total_tool_uses', (
      select count(*) from public.analytics_events
      where event_type = 'tool_use'
        and created_at >= start_at
        and created_at < (end_day + 1)::timestamp at time zone 'Asia/Shanghai'
    ),
    'prev_total_views', (
      select count(*) from public.analytics_daily_visitors
      where visit_day between prev_start and prev_end
    ),
    'prev_unique_visitors', (
      select count(distinct visitor_id) from public.analytics_daily_visitors
      where visit_day between prev_start and prev_end
    ),
    'prev_total_tool_uses', (
      select count(*) from public.analytics_events
      where event_type = 'tool_use'
        and created_at >= prev_start::timestamp at time zone 'Asia/Shanghai'
        and created_at < prev_end_at
    ),
    'new_visitors', (
      select count(*) from (
        select visitor_id
        from public.analytics_daily_visitors
        group by visitor_id
        having min(visit_day) between start_day and end_day
      ) n
    ),
    'returning_visitors', (
      select count(distinct v.visitor_id)
      from public.analytics_daily_visitors v
      where v.visit_day between start_day and end_day
        and exists (
          select 1 from public.analytics_daily_visitors p
          where p.visitor_id = v.visitor_id and p.visit_day < start_day
        )
    ),
    'tools', coalesce((
      select jsonb_agg(jsonb_build_object('slug', tool_slug, 'uses', uses) order by uses desc)
      from (
        select tool_slug, count(*) uses
        from public.analytics_events
        where event_type = 'tool_use'
          and created_at >= start_at
          and created_at < (end_day + 1)::timestamp at time zone 'Asia/Shanghai'
          and tool_slug is not null
        group by tool_slug
      ) t
    ), '[]'::jsonb),
    'daily', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'date', day_label,
          'views', view_count,
          'visitors', visitor_count,
          'uses', use_count
        ) order by bucket_day
      )
      from (
        select
          d.bucket_day,
          to_char(d.bucket_day, 'YYYY-MM-DD') as day_label,
          count(v.visitor_id) as view_count,
          count(distinct v.visitor_id) as visitor_count,
          coalesce(u.uses, 0) as use_count
        from generate_series(start_day, end_day, interval '1 day') as d(bucket_day)
        left join public.analytics_daily_visitors v
          on v.visit_day = d.bucket_day::date
        left join (
          select (created_at at time zone 'Asia/Shanghai')::date as use_day, count(*) as uses
          from public.analytics_events
          where event_type = 'tool_use'
            and created_at >= start_at
            and created_at < (end_day + 1)::timestamp at time zone 'Asia/Shanghai'
          group by 1
        ) u on u.use_day = d.bucket_day::date
        group by d.bucket_day, u.uses
      ) as daily_rows
    ), '[]'::jsonb),
    'devices', coalesce((
      select jsonb_agg(jsonb_build_object('name', name, 'count', amount) order by amount desc)
      from (
        select coalesce(device, 'unknown') name, count(*) amount
        from public.analytics_daily_visitors
        where visit_day between start_day and end_day
        group by device
      ) x
    ), '[]'::jsonb),
    'browsers', coalesce((
      select jsonb_agg(jsonb_build_object('name', name, 'count', amount) order by amount desc)
      from (
        select coalesce(browser, 'Other') name, count(*) amount
        from public.analytics_daily_visitors
        where visit_day between start_day and end_day
        group by browser
      ) x
    ), '[]'::jsonb),
    'referrers', coalesce((
      select jsonb_agg(jsonb_build_object('name', name, 'count', amount) order by amount desc)
      from (
        select
          case
            when referrer is null or referrer = '' or lower(referrer) = 'direct' then '直接访问'
            when referrer ilike '%utilora.github.io%' or referrer ilike '%localhost%' then '站内跳转'
            else referrer
          end as name,
          count(*) amount
        from public.analytics_daily_visitors
        where visit_day between start_day and end_day
        group by 1
        order by amount desc
        limit 10
      ) x
    ), '[]'::jsonb),
    'pages', coalesce((
      select jsonb_agg(jsonb_build_object('path', page_path, 'views', amount) order by amount desc)
      from (
        select coalesce(path, '/') page_path, count(*) amount
        from public.analytics_daily_visitors
        where visit_day between start_day and end_day
        group by path
        order by amount desc
        limit 10
      ) x
    ), '[]'::jsonb)
  ) into result;
  return result;
end
$$;
revoke all on function public.get_analytics_summary(integer, date, date) from public, anon;
grant execute on function public.get_analytics_summary(integer, date, date) to authenticated;
